#!/bin/bash
docker system prune -af
# Create the Backend JAR file
cd server
mvn clean package -DskipTests

# Build the Docker Images
cd ..
docker-compose build

# Tag the Docker Images 
docker tag app_nginx:latest public.ecr.aws/neservice/nginx:latest
docker tag app_client:latest public.ecr.aws/neservice/client:latest
docker tag app_backend:latest public.ecr.aws/neservice/backend:latest

# Push to Elastic Container Registery
docker push public.ecr.aws/neservice/nginx:latest
docker push public.ecr.aws/neservice/client:latest
docker push public.ecr.aws/neservice/backend:latest
