#!/bin/bash
docker system prune -af
# Create the Backend JAR file
cd server
mvn clean package -DskipTests

# Build the Docker Images
cd ..
docker-compose build

# Get Permissions to Write to Repository
/usr/local/bin/aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/neservice

# Tag the Docker Images 
docker tag app_nginx:latest public.ecr.aws/neservice/nginx:latest
docker tag app_client:latest public.ecr.aws/neservice/client:latest
docker tag app_backend:latest public.ecr.aws/neservice/backend:latest

# Push to Elastic Container Registery
docker push public.ecr.aws/neservice/nginx:latest
docker push public.ecr.aws/neservice/client:latest
docker push public.ecr.aws/neservice/backend:latest
