package com.neservice.models;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

@DynamoDBTable(tableName = "history")
public class History {
	// Members of Table
	@JsonProperty("id") private String id;
	@JsonProperty("provider") private String provider;
	@JsonProperty("reserver") private String reserver;
	@JsonProperty("history") private List<HistoryItem> history = new ArrayList<>();
	
	// Default Constructor
	public History() {
		
	}
	
	// Override Constructor
	public History(String id, String provider, String reserver) {
		this.id = id;
		this.provider = provider;
		this.reserver = reserver;
	}
	
	// Getters
	@DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    public String getId() {
    	return id;
    }
    
    @DynamoDBAttribute
	public String getProvider() {
		return provider;
	}
    
    @DynamoDBAttribute
	public String getReserver() {
		return reserver;
	}
    
    
    @DynamoDBAttribute
	public List<HistoryItem> getHistory() {
		return history;
	}

	// Setters 
	public void setProvider(String provider) {
		this.provider = provider;
	}
	
	public void setReserver(String reserver) {
		this.reserver = reserver;
	}
	
	// Array Functionality
	public void addHistory(HistoryItem newHistory) {
		history.add(newHistory);
	}
	
	public void removeHistory(HistoryItem oldHistory) {
		history.remove(oldHistory);
	}
	
	// Comparison 
	@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        History comp = (History) o;
        return id.equals(comp.id);
    }
}