package com.neservice.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "service")
public class Service {
	// Members of Table
	private String id;
	private String email;
	private String title;
	private String desc;
	private String price;
	private int duration;

	// Default Constructor
	public Service() {
		
	}
	
	// Override Constructor
	public Service(String id, String email, String title, String desc, String price, int duration) {
		this.id = id;
		this.email = email;
		this.title = title;
		this.desc = desc;
		this.price = price;
		this.duration = duration;
	}
	
	// Getters
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    public String getId() {
    	return id;
    }
    
    @DynamoDBAttribute
	public String getEmail() {
		return email;
	}
    
    @DynamoDBAttribute
	public String getTitle() {
		return title;
	}
    
    @DynamoDBAttribute
	public String getDesc() {
		return desc;
	}

    @DynamoDBAttribute
	public String getPrice() {
		return price;
	}
    
    @DynamoDBAttribute
	public int getDuration() {
		return duration;
	}

	// Setters
    public void setId(String id) {
    	this.id = id;
    }
    
	public void setEmail(String email) {
		this.email = email;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public void displayService() {
		System.out.println("ID: "+this.id);
		System.out.println("Email: "+this.email);
		System.out.println("Service Title: "+this.title);
		System.out.println("Service Description: "+this.desc);
		System.out.println("Service Price: "+this.price);
		System.out.println("Service Duration: "+this.duration);
	}
	
	// Comparison 
	@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        Service comp = (Service) o;
        return id.equals(comp.id);
    }
}