package com.neservice.user;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "login")
public class User {
	// Members of Table
	private String username;
	private String password;

	// Default Constructor
	public User() {
		
	}
	
	// Override Constructor
	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}
	
	// Getters
    @DynamoDBHashKey(attributeName="username")
	public String getUsername() {
		return username;
	}
    
    @DynamoDBAttribute
	public String getPassword() {
		return password;
	}
	
	// Setters
	public void setUsername(String username) {
		this.username = username;
	}
	public void setPassword(String password) {
		this.password = password;
	}

	public void displayUser() {
		System.out.println("Username: "+this.username);
		System.out.println("Password: "+this.password);
	}
	
	// Comparison 
	@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        User comp = (User) o;
        return username.equals(comp.username);
    }
}